kind: pipeline
type: ssh
name: manager-server

server:
  host:
    from_secret: ssh-prod-server
  user:
    from_secret: ssh-prod-user
  password:
    from_secret: ssh-prod-pw

steps:
  - name: build
    commands:
      - mvn clean install -DskipTests
  - name: depoly
    commands:
      - mv ./so-manager-admin/target/so-manager-admin.jar ./
      - docker stop manager-server && docker rm manager-server && docker rmi manager-server
      - docker build -f ./so-manager-admin/Dockerfile -t manager-server .
      - docker run -d -p 9060:8080 -v /home/sleepy/3-mount/theater-0:/0-Cinema0 -v /home/sleepy/3-mount/theater-1:/0-Cinema1 --name manager-server manager-server
